version: '3.3'
services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=bookmarksbox
      - POSTGRES_USER=bb
      - POSTGRES_PASSWORD=bbpassword
      - TZ=Europe/Paris
      - PGTZ=Europe/Paris
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  composer:
    image: composer
    volumes:
      - .:/usr/src/app
    command: install
  node:
    build:
      context: ./tools/docker/node/
    command: yarn run
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
  php:
    image: php:7.2-fpm
    restart: unless-stopped
    environment:
      - APP_ENV=production
    depends_on:
      - db
  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - .:/var/www/
      - ./tools/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - php

volumes:
  db-data:
    driver: local
